
CREATE DATABASE WR_DATA;
USE WR_DATA;

DROP TABLE TBL_WAREHOUSE;
CREATE TABLE TBL_WAREHOUSE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(200) NOT NULL,
    SKU VARCHAR(25) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0,
    MIN_STOCK INT NOT NULL DEFAULT 0,
    ADDR_WR VARCHAR(200) NOT NULL,
    CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- TBL_USER 

DROP TABLE TBL_USERS;
CREATE TABLE TBL_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (200) NOT NULL,
    EMAIL VARCHAR(200),
    ROLE ENUM("USER", "MANAGER","ADMIN"),
    REG_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TBL_INV_MOVEMENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    WR_ID INT NOT NULL,
    TYPE ENUM ('INCOMING', 'OUTGOING') NOT NULL,
    QUANTITY INT NOT NULL,
    CREATED_BY INT NULL,
    REG_TD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (WR_ID) REFERENCES TBL_WAREHOUSE(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES TBL_USERS(ID) ON DELETE SET NULL
);

CREATE TABLE TBL_SHIPMENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    WR_ID INT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0,
    STATUS ENUM('PENDING', ' APPROVED', 'REJECTED') DEFAULT 'PENDING',
    REQUESTED_BY INT NOT NULL,
    APPROVED_BY INT NULL,
    DESTINATION VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (WR_ID) REFERENCES TBL_WAREHOUSE(ID) ON DELETE CASCADE,
    FOREIGN KEY (REQUESTED_BY) REFERENCES TBL_USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (APPROVED_BY) REFERENCES TBL_USERS(ID) ON DELETE SET NULL
);


CREATE TABLE TBL_CONSUMERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CONTACT VARCHAR(255) NOT NULL,
    ADDRESS TEXT NOT NULL,
    COMP_TY VARCHAR(255),
    IS_VERIFY BOOLEAN DEFAULT FALSE
);


CREATE TABLE CONSUMER_REQUEST(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    WR_ID INT,
    QUANTITY INT NOT NULL,
    REQUESTED_BY INT NOT NULL,
    STATUS ENUM ('PENDING' , 'VERIFY', 'APPROVED', 'RECEIVED') DEFAULT 'PENDING',
    VERIFY_BY INT NULL,
    APPROVED_BY INT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (WR_ID) REFERENCES TBL_WAREHOUSE(ID) ON DELETE CASCADE,
    FOREIGN KEY (REQUESTED_BY) REFERENCES TBL_CONSUMERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (VERIFY_BY) REFERENCES TBL_USERS(ID) ON DELETE SET NULL,
    FOREIGN KEY (APPROVED_BY) REFERENCES TBL_USER(ID) ON DELETE SET NULL
);


SHOW TABLES;

SELECT * FROM TBL_INV_MOVEMENT;
SELECT * FROM TBL_SHIPMENT;
SELECT * FROM TBL_USERS;
SELECT * FROM TBL_CONSUMERS;
SELECT * FROM TBL_WAREHOUSE;

INSERT INTO TBL_WAREHOUSE(NAME, SKU, QUANTITY, MIN_STOCK, ADDR_WR, CREATE_AT) VALUES ("WR01", "00910291WR000001", 50000, 100, "MERDEKA CITY", NOW());
INSERT INTO TBL_WAREHOUSE(NAME, SKU, QUANTITY, MIN_STOCK, ADDR_WR, CREATE_AT) VALUES ("WR02", "00910291WR000002", 100000, 5000, "MUARA CITY", NOW());


